
all_groups:
   {"compartment": ['endothelial', 'epithelial', 'lymphoid', 'myeloid', 'stromal'],
    "broad": ['B cell',
 'T cell',
 'alveolar epithelial cell type 2',
 'artery cell',
 'capillary cell',
 'ciliated cell',
 'dendritic cell',
 'endothelial cell',
 'fibroblast',
 'lymphatic cell',
 'macrophage',
 'monocyte',
#  'myofibroblast cell',
 'natural killer T cell',
 'natural killer cell',
 'pericyte cell',
 'pericyte cell_smooth muscle cell',
 'plasma cell',
 'natural killer cell_T cell (PF)',
 'vein cell']
,
    "narrow": ['B cell',
 'T cell (CD4+)',
 'T cell (CD8+)',
 'adventitial fibroblast',
 'alveolar epithelial cell type 2',
 'alveolar fibroblast',
 'alveolar macrophage',
 'alveolar macrophage (PF)',
 'artery cell',
 'capillary aerocyte cell',
 'capillary cell',
 'ciliated cell',
 'conventional dendritic cell',
 'lymphatic cell',
 'monocyte',
 'natural killer T cell',
 'natural killer cell',
 'natural killer cell_T cell (PF)',
 'pericyte',
 'plasma cell',
 'plasmacytoid dendritic cell',
 'vein cell']
}
compartment_narrow: {'endothelial': ['capillary cell',
  'capillary aerocyte cell',
  'vein cell',
  'artery cell',
  'lymphatic cell'],
 'epithelial': ['alveolar epithelial cell type 2', 'ciliated cell'],
 'lymphoid': ['B cell',
  'natural killer cell',
  'CD8+ T cell',
  'natural killer T cell',
  'CD4+ T cell',
  'plasma cell',
  'proliferating natural killer cell_T cell'],
 'myeloid': ['monocyte',
  'alveolar macrophage',
  'conventional dendritic cell',
  'proliferating alveolar macrophage',
  'plasmacytoid dendritic cell'],
 'stromal': [
#      'myofibroblast cell',
  'adventitial fibroblast',
  'alveolar fibroblast',
  'pericyte cell']}
significant_compartment_narrow: {
    'endothelial': ['Capillary', 'Capillary Aerocyte', 'Lymphatic'],
    'epithelial': ['Alveolar Epithelial Type 2'],
    'lymphoid': ['CD4+ T', 'Natural Killer', 'Plasma', 'Proliferating NK/T'],
    'myeloid': [
        'Macrophage', 'Monocyte', 'Myeloid Dendritic', 'Proliferating Macrophage'],
    'stromal': ['Adventitial Fibroblast', 'Alveolar Fibroblast']}
